### ISSUE TITLE
change link to mapbox basemap

### ISSUE THREAD

**Issue by gretacv** [Vizzuality/copernicus-climate#15]
https://github.com/Vizzuality/copernicus-climate/blob/6123b59a8252d9e61373a00cc3c7abae35121dc1/src/const/constants.js#L71
 line should be:
`export const MAPBOX_STYLE_DEFAULT = 'mapbox://styles/copernicus-forests/ckagm1ll90os61il7lqwd06cg';`

**Comment by blayhem** [comment]
Solved in [f8afd9a](https://github.com/Vizzuality/copernicus-climate/commit/f8afd9ab4607231aa6e1ab348754879e43e012a9).
