### ISSUE TITLE
missing period

### ISSUE THREAD

**Issue by gretacv** [Vizzuality/copernicus-climate#18]
A period is needed at the end of the line

`Thermal Comfort is only available for the <Link to={`/${gid}/historical/${theme}`}>historical</Link> period.`

https://github.com/Vizzuality/copernicus-climate/blob/364fa6562f46c24ec91263719d0ae175648e94d1/src/pages/home/component.jsx#L456

**Comment by blayhem** [comment]
Solved on https://github.com/Vizzuality/copernicus-climate/commit/e7730e9054783b761cf281bb15c0f8a0bcb94595.
