### ISSUE TITLE
Copy issue

### ISSUE THREAD

**Issue by gretacv** [Vizzuality/copernicus-climate#20]
The line should say:
`<h4>Thermal stress events per month (averaged per geometry, data available from 2004)</h4> :`
https://github.com/Vizzuality/copernicus-climate/blob/2516e1b9fe508f7640355f70008e69735ff938b7/src/components/chart/component.jsx#L287

**Comment by blayhem** [comment]
Solved on a4c977146db1edb3ac9746857bd3bf976f7226b9, thanks!
